apiVersion: v1
kind: Secret
metadata:
  name: catalogue-db-creds
  labels:
type: Opaque
data:
  username: {{ .Values.cataloguedb.secret_values.username | b64enc | quote }}
  password: {{ .Values.cataloguedb.secret_values.password | b64enc | quote }}
  mysql_root_password: {{ .Values.cataloguedb.secret_values.mysql_root_password | b64enc | quote }}
  mysql_database: {{ .Values.cataloguedb.secret_values.mysql_database | b64enc | quote }}
